# Generated by Django 4.1 on 2023-02-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_role_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Permissions',
        ),
    ]
