# Generated by Django 4.1 on 2023-02-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_permission_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='permission',
            new_name='permissions',
        ),
    ]
